esphome:
  name: "bedroom-light"
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "xod"                    # Langsung ditulis
  password: "05081992"             # Langsung ditulis
  
  ap:
    ssid: "BedHotspot"
    password: "fallback123"

api:
  encryption:
    key: "abc123def456ghi789jkl012mno345pqr678stu901"

ota:
  password: "ota_update_secure"

logger:

light:
  - platform: gpio
    pin: GPIO4
    name: "Bedroom Light"
